[tool.poetry]
name = "jane-street-may-2024"
version = "0.1.0"
description = ""
authors = ["Matt"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fire = "^0.6.0"
tqdm = "^4.66.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
